### ISSUE TITLE
Meta analysis

### ISSUE THREAD

**Issue by jazznbass** [jazznbass/scan#22]
We have an increasing demand for meta analysis.

Instead of implementing a meta-analysis within every function, a better way might be to have a separate function that takes the return of various analyses and conducts a meta analyses on them.

The generic function might be:
meta_analysis()

The method dispatch might be a bit scruffy: All our S3 objects have "two" classes (sc and a specific class; this is not very nice because actually this should indicate an inheritance relationship!):
1. old school dirty way -> one method for sc class and go on from there with calls depending on the second class argument.
2. a workaround -> a method for class sc calls the next method for the second class
3. clean -> rewrite all classnames (e.g. sc_describe, sc_plm).
I am in favour of the third method. But it might break some code if someone out there worked with our current classes - but that is highly improbable.

**Comment by jazznbass** [comment]
> 3. clean -> rewrite all classnames (e.g. sc_describe, sc_plm).
> I am in favour of the third method. But it might break some code if someone out there worked with our current classes - but that is highly improbable.

I started to rename the classes and create the respective methods for print and export. I am not sure all changes will be made for the 0.53 release. Maybe it is better to postpone the release until thjs is completet?

**Comment by researchtool** [comment]
Your call! I'd love to see a new version goo live,  but excluding the class changes is probably too much additional work. So, fine with me.  :)
