### ISSUE TITLE
problem with csv data import (lost mt)

### ISSUE THREAD

**Issue by researchtool** [jazznbass/scan#64]
When importing data from a csv I'm losing the measurement times (scan 0.54.1).
Import works but the scdf doesn't have a mt variable.

reproducible example with attached csv-file:
read_scdf("bsp-import.csv")
read_scdf("bsp-import.csv", mvar = "mt")

`dat <- readSC("bsp-import.csv")
Loaded 2 cases.
 str(dat)
List of 2
 $ Hans :'data.frame':	6 obs. of  3 variables:
  ..$ values: int [1:6] 45 46 45 54 53 52
  ..$ phase : Factor w/ 2 levels "A","B": 1 1 1 2 2 2
  ..$ case  : Factor w/ 2 levels "Hans","Wurst": 1 1 1 1 1 1
 $ Wurst:'data.frame':	6 obs. of  3 variables:
  ..$ values: int [1:6] 45 46 45 54 53 52
  ..$ phase : Factor w/ 2 levels "A","B": 1 1 1 2 2 2
  ..$ case  : Factor w/ 2 levels "Hans","Wurst": 2 2 2 2 2 2
  attr(*, "class")= chr [1:2] "scdf" "list"
  attr(*, "scdf")=List of 3
  ..$ var.phase : chr "phase"
  ..$ var.values: chr "values"
  ..$ var.mt    : chr "mt"`

**Comment by jazznbass** [comment]
solved in 0.54.2
