### ISSUE TITLE
Tau-U Meta, Method "Complete" and Confidence Intervals Above 1

### ISSUE THREAD

**Issue by jazznbass** [jazznbass/scan#91]
### Discussed in https://github.com/jazznbass/scan/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **gjones1219** December 27, 2022</sup>
Hello again Jurgen! I hope you are taking good care. I had a quick question about the output for Tau-U meta.

In the "Jazz" book, it says that for Tau-U meta, method = "complete", values for for Tau-U output will range from [-1,1]. However, when one looks at the confidence intervals that are returned by the Tau-U meta function when using method = "complete", the values for the 95% Confidence Intervals are sometimes outside of this range (i.e., above and below [-1,1]). Please see the example in the scan book at this link: https://jazznbass.github.io/scan-Book/ch_overlapping_indices.html#tau-u (specifically, look at the output for the following line of code: tau_u(exampleAB) )

Can you please explain this discrepancy? Thanks so much!

Grant</div>

**Comment by jazznbass** [comment]
CIs were calculated from the estimated standard errors of tau without Fisher Z transformation. This could lead to implausible values for very few measurements and high tau values.
I have rewritten the ci calculation code and implemented two different methods for estimating the se of tau_z for 0.55.7 (current development version) which will be the basis for the upcoming 0.56 cran release.
I have added more detailed explanations to the next version of the scan book (23-02).

**Comment by gjones1219** [comment]
Thank you!

Grant
